"use client";
import { AdminFieldIcon } from "@/components/admin/shared/form-fields";
import { AdminInput, AdminSelect, AdminTextarea } from "@/components/admin/shared/form-fields";
import { useState } from "react";
import { MagnifyingGlassIcon, PlusIcon, PencilSquareIcon, TrashIcon, XMarkIcon } from "@heroicons/react/24/outline";
import { ModuleHeader } from "@/components/admin/shared/module-header";

type QuoteStatus = "DRAFT" | "SENT" | "ACCEPTED" | "DECLINED" | "EXPIRED";
type Quote = { id: string; reference: string; client: string; status: QuoteStatus; totalMinor: number; items: string[] };
const statusMap: Record<QuoteStatus, { label: string; style: string }> = {
 DRAFT: { label: "Draft", style: "bg-slate-100 text-slate-600" },
 SENT: { label: "Sent", style: "bg-blue-50 text-blue-700" },
 ACCEPTED: { label: "Accepted", style: "bg-emerald-50 text-emerald-700" },
 DECLINED: { label: "Declined", style: "bg-red-50 text-red-700" },
 EXPIRED: { label: "Expired", style: "bg-amber-50 text-amber-700" },
};
const initialQuotes: Quote[] = [
 { id: "quote-1", reference: "QT-2026-0041", client: "Northgate Academy", status: "SENT", totalMinor: 124000000, items: ["School management portal", "Implementation support"] },
 { id: "quote-2", reference: "QT-2026-0040", client: "Prime Logistics", status: "ACCEPTED", totalMinor: 248000000, items: ["Corporate website development"] },
 { id: "quote-3", reference: "QT-2026-0039", client: "Horizon Group", status: "DRAFT", totalMinor: 86000000, items: ["Staff training programme", "Training materials"] },
];
const currency = (minor: number) => new Intl.NumberFormat("en-NG", { style: "currency", currency: "NGN", maximumFractionDigits: 0 }).format(minor / 100);
const inputClass = "mt-2 w-full rounded-xl border border-slate-200 bg-slate-50/50 px-3 py-2.5 text-sm text-slate-700";

export function QuotationManager() {
 const [quotes, setQuotes] = useState(initialQuotes);
 const [search, setSearch] = useState("");
 const [status, setStatus] = useState("ALL");
 const [editor, setEditor] = useState<Quote | null>(null);
 const [deleting, setDeleting] = useState<Quote | null>(null);
 const [notice, setNotice] = useState("");
 const filtered = quotes.filter(quote => (status === "ALL" || quote.status === status) && (quote.reference + " " + quote.client + " " + quote.items.join(" ")).toLowerCase().includes(search.toLowerCase()));
 function save(event: React.FormEvent<HTMLFormElement>) {
  event.preventDefault(); if (!editor) return;
  setQuotes(current => current.some(item => item.id === editor.id) ? current.map(item => item.id === editor.id ? editor : item) : [...current, editor]);
  setNotice(editor.reference + " updated in this session."); setEditor(null);
 }
 return <div className="space-y-6">
  <ModuleHeader title="Quotations" description="Prepare, review, and track client quotations." group="Finance" />
  <section aria-label="Quotation summary" className="grid grid-cols-2 gap-4 xl:grid-cols-4">{(["DRAFT", "SENT", "ACCEPTED", "EXPIRED"] as const).map(key => <article key={key} className="admin-shadow-soft rounded-2xl bg-white p-5"><span className={"inline-flex rounded-lg px-2 py-1 text-[10px] font-semibold " + statusMap[key].style}>{statusMap[key].label}</span><p className="mt-5 text-2xl font-bold text-[#172B3A]">{quotes.filter(quote => quote.status === key).length}</p></article>)}</section>
  <div className="admin-shadow-soft flex flex-col gap-3 rounded-2xl bg-white p-4 sm:flex-row"><div className="relative min-w-0 flex-1"><MagnifyingGlassIcon className="absolute top-3 left-3 h-4 w-4 text-slate-400" /><input aria-label="Search quotations" value={search} onChange={event => setSearch(event.target.value)} placeholder="Search reference, client, or item" className="w-full rounded-xl border border-slate-200 bg-slate-50/50 py-2.5 pr-3 pl-9 text-xs" /></div><select aria-label="Filter quotations by status" value={status} onChange={event => setStatus(event.target.value)} className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-xs text-slate-600"><option value="ALL">All statuses</option>{Object.entries(statusMap).map(([key, value]) => <option key={key} value={key}>{value.label}</option>)}</select><button type="button" onClick={() => setEditor({ id: crypto.randomUUID(), reference: "QT-" + new Date().getFullYear() + "-NEW", client: "", status: "DRAFT", totalMinor: 0, items: [""] })} className="button"><PlusIcon className="h-4 w-4" />New quotation</button></div>
  <p role="status" className="text-xs text-slate-500">{notice || ("Showing " + filtered.length + " of " + quotes.length + " quotations")}</p>
  <section className="space-y-4">{filtered.map(quote => <article key={quote.id} className="admin-shadow-soft rounded-2xl bg-white p-5 sm:p-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="mb-0! break-words text-xs! font-semibold text-[#172B3A] sm:text-sm!">{quote.reference}</h3><span className={"rounded-lg px-2 py-1 text-[10px] font-semibold " + statusMap[quote.status].style}>{statusMap[quote.status].label}</span></div><p className="mt-2 text-sm text-slate-700">{quote.client}</p><ul className="mt-3 flex flex-wrap gap-x-5 gap-y-1 text-xs text-slate-500">{quote.items.map(item => <li key={item} className="ml-4 list-disc">{item}</li>)}</ul></div><div className="flex items-center justify-between gap-4 lg:justify-end"><p className="text-lg font-bold text-[#172B3A]">{currency(quote.totalMinor)}</p><button type="button" aria-label={"Edit " + quote.reference} onClick={() => setEditor({ ...quote, items: [...quote.items] })} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><PencilSquareIcon className="h-4 w-4" /></button><button type="button" aria-label={"Delete " + quote.reference} onClick={() => setDeleting(quote)} className="rounded-lg p-2 text-red-600 hover:bg-red-50"><TrashIcon className="h-4 w-4" /></button></div></div></article>)}</section>
  {!filtered.length && <div className="admin-shadow-soft rounded-2xl bg-white px-6 py-14 text-center"><p className="text-sm text-slate-600">No quotations found</p><p className="mt-1 text-xs text-slate-500">Try another filter or create a new quotation.</p></div>}
  {editor && <div className="fixed inset-0 z-50 grid place-items-center bg-[#172B3A]/40 p-4 backdrop-blur-sm"><div role="dialog" aria-modal="true" className="admin-shadow-popover max-h-[90dvh] w-full max-w-xl overflow-y-auto rounded-2xl bg-white p-5 sm:p-6"><div className="flex items-start justify-between"><div><h3 className="text-sm! font-semibold text-[#172B3A]">{quotes.some(item => item.id === editor.id) ? "Edit" : "New"} quotation</h3><p className="mt-1 text-xs text-slate-500">Update the quotation details for this session.</p></div><button type="button" aria-label="Close" onClick={() => setEditor(null)}><XMarkIcon className="h-5 w-5 text-slate-500" /></button></div><form onSubmit={save} className="mt-5 space-y-4"><label className="block text-xs font-semibold text-slate-700"><AdminFieldIcon fieldLabel="Reference" />Reference<AdminInput fieldLabel="Reference" required value={editor.reference} onChange={event => setEditor({ ...editor, reference: event.target.value })} className={inputClass} /></label><label className="block text-xs font-semibold text-slate-700"><AdminFieldIcon fieldLabel="Client" />Client<AdminInput fieldLabel="Client" required value={editor.client} onChange={event => setEditor({ ...editor, client: event.target.value })} className={inputClass} /></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-xs font-semibold text-slate-700"><AdminFieldIcon fieldLabel="Status" />Status<AdminSelect fieldLabel="Status" value={editor.status} onChange={event => setEditor({ ...editor, status: event.target.value as QuoteStatus })} className={inputClass}>{Object.entries(statusMap).map(([key, value]) => <option key={key} value={key}>{value.label}</option>)}</AdminSelect></label><label className="block text-xs font-semibold text-slate-700"><AdminFieldIcon fieldLabel="Total (minor units)" />Total (minor units)<AdminInput fieldLabel="Total (minor units)" required type="number" min="0" value={editor.totalMinor} onChange={event => setEditor({ ...editor, totalMinor: Number(event.target.value) })} className={inputClass} /></label></div><label className="block text-xs font-semibold text-slate-700"><AdminFieldIcon fieldLabel="Line items" />Line items<AdminTextarea fieldLabel="Line items" rows={4} value={editor.items.join("\n")} onChange={event => setEditor({ ...editor, items: event.target.value.split("\n") })} className={inputClass} /><span className="mt-1 block font-normal text-slate-500">One item per line.</span></label><div className="flex justify-end gap-2 border-t border-slate-100 pt-4"><button type="button" onClick={() => setEditor(null)} className="rounded-lg px-3 py-2 text-xs font-semibold text-slate-600 hover:bg-slate-100">Cancel</button><button type="submit" className="button">Save quotation</button></div></form></div></div>}
  {deleting && <div className="fixed inset-0 z-50 grid place-items-center bg-[#172B3A]/40 p-4 backdrop-blur-sm"><div role="alertdialog" aria-modal="true" className="admin-shadow-popover w-full max-w-md rounded-2xl bg-white p-6"><h3 className="text-sm! font-semibold text-[#172B3A]">Delete quotation?</h3><p className="mt-3 text-sm leading-6 text-slate-500">Remove {deleting.reference} from this session?</p><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={() => setDeleting(null)} className="rounded-lg px-3 py-2 text-xs font-semibold text-slate-600 hover:bg-slate-100">Cancel</button><button type="button" onClick={() => { setQuotes(current => current.filter(item => item.id !== deleting.id)); setNotice(deleting.reference + " removed from this session."); setDeleting(null); }} className="rounded-lg bg-red-600 px-4 py-2 text-xs font-semibold text-white">Delete</button></div></div></div>}
 </div>;
}

