"use client";
import { useState } from "react";
import Link from "next/link";
import { MagnifyingGlassIcon, ChatBubbleLeftRightIcon, ArrowRightIcon, PlusIcon, PencilSquareIcon, TrashIcon, XMarkIcon } from "@heroicons/react/24/outline";
import type { Inquiry } from "@/types/modules";
import { ModuleHeader } from "@/components/admin/shared/module-header";
import { inquiryStatuses } from "./inquiry-data";

export function InquiryDirectory({ inquiries, contacts }: { inquiries: Inquiry[]; contacts: Record<string, { name: string; email: string }> }) {
 const [rows, setRows] = useState(inquiries);
 const [search, setSearch] = useState("");
 const [status, setStatus] = useState("ALL");
 const [editor, setEditor] = useState<Inquiry | null>(null);
 const [deleting, setDeleting] = useState<Inquiry | null>(null);
 const query = search.trim().toLowerCase();
 const filtered = rows.filter(item => (status === "ALL" || item.status === status) && [item.reference, item.subject, contacts[item.contactId]?.name ?? ""].some(value => value.toLowerCase().includes(query)));
 function save(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!editor?.subject.trim() || !editor.reference.trim()) return; setRows(current => current.some(item => item.id === editor.id) ? current.map(item => item.id === editor.id ? editor : item) : [...current, editor]); setEditor(null); }
 return <div className="space-y-6">
  <ModuleHeader title="Inquiries" description="Keep customer conversations moving, from first contact to resolution." group="Customers" />
  <section aria-label="Inquiry summary" className="grid grid-cols-2 gap-4 xl:grid-cols-4">{(["NEW", "OPEN", "AWAITING_CUSTOMER", "RESOLVED"] as const).map(key => <article key={key} className="admin-shadow-soft rounded-2xl bg-white p-5"><span className={"inline-flex rounded-lg px-2 py-1 text-[10px] font-semibold " + inquiryStatuses[key].style}>{inquiryStatuses[key].label}</span><p className="mt-5 text-2xl font-bold text-[#172B3A]">{rows.filter(item => item.status === key).length}</p></article>)}</section>
  <section className="admin-shadow-soft overflow-hidden rounded-2xl bg-white">
   <div className="space-y-4 p-5 sm:p-6"><div><h3 className="text-xs! leading-snug! font-semibold text-[#172B3A] sm:text-sm!">Inquiry inbox</h3><p className="mt-1 text-xs text-slate-500">Find a conversation and manage its details.</p></div><div className="flex flex-col gap-3 sm:flex-row"><div className="relative min-w-0 flex-1"><MagnifyingGlassIcon className="absolute top-3 left-3 h-4 w-4 text-slate-400" /><input aria-label="Search inquiries" type="search" value={search} onChange={event => setSearch(event.target.value)} placeholder="Search reference, subject, or customer…" className="w-full rounded-xl border border-slate-200 bg-slate-50/50 py-2.5 pr-3 pl-9 text-xs" /></div><select aria-label="Inquiry status" value={status} onChange={event => setStatus(event.target.value)} className="rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-xs text-slate-600"><option value="ALL">All statuses</option>{Object.entries(inquiryStatuses).map(([key, value]) => <option key={key} value={key}>{value.label}</option>)}</select><button type="button" onClick={() => setEditor({ id: crypto.randomUUID(), reference: "INQ-NEW", contactId: Object.keys(contacts)[0] ?? "", businessUnitId: "demo", categoryId: "digital-services", serviceId: null, subject: "", status: "NEW", assignedTo: null, isDemo: true, createdAt: Date.now(), updatedAt: Date.now() })} className="inline-flex items-center justify-center gap-2 rounded-lg bg-[#FFA64D] px-4 py-2.5 text-xs font-semibold text-[#172B3A]"><PlusIcon className="h-4 w-4" />New inquiry</button></div></div>
   <div className="hidden grid-cols-[2fr_1fr_1fr_auto] gap-4 border-y border-slate-100 bg-slate-50/70 px-6 py-2.5 text-[10px] font-semibold uppercase tracking-wide text-slate-500 md:grid"><span>Inquiry</span><span>Customer</span><span>Status</span><span>Actions</span></div>
   <ul className="divide-y divide-slate-100">{filtered.map(item => <li key={item.id} className="grid gap-3 px-5 py-4 hover:bg-slate-50/70 sm:px-6 md:grid-cols-[2fr_1fr_1fr_auto] md:items-center md:gap-4"><Link href={"/admin/inquiries/" + item.id} className="min-w-0"><p className="text-[11px] font-semibold text-[#172B3A]">{item.reference}</p><p className="mt-1 break-words text-sm text-slate-700">{item.subject}</p></Link><p className="text-xs text-slate-500">{contacts[item.contactId]?.name ?? "—"}</p><span className={"w-fit rounded-lg px-2 py-1 text-[10px] font-semibold " + inquiryStatuses[item.status].style}>{inquiryStatuses[item.status].label}</span><div className="flex items-center gap-1"><button type="button" aria-label={"Edit " + item.reference} onClick={() => setEditor({ ...item })} className="cursor-pointer rounded-lg p-2 text-slate-500 hover:bg-slate-100"><PencilSquareIcon className="h-4 w-4" /></button><button type="button" aria-label={"Delete " + item.reference} onClick={() => setDeleting(item)} className="cursor-pointer rounded-lg p-2 text-red-600 hover:bg-red-50"><TrashIcon className="h-4 w-4" /></button><ArrowRightIcon className="ml-1 h-3.5 w-3.5 text-slate-400" /></div></li>)}</ul>
   {!filtered.length && <div className="px-6 py-14 text-center"><ChatBubbleLeftRightIcon className="mx-auto h-8 w-8 text-slate-400" /><p className="mt-3 text-sm text-slate-600">No inquiries found</p><p className="mt-1 text-xs text-slate-500">Try a different search or add a new inquiry.</p></div>}
   <p role="status" className="border-t border-slate-100 px-5 py-3 text-xs text-slate-500 sm:px-6">Showing {filtered.length} of {rows.length} inquiries</p>
  </section>
  {editor && <div className="fixed inset-0 z-50 grid place-items-center bg-[#172B3A]/40 p-4 backdrop-blur-sm"><div role="dialog" aria-modal="true" className="admin-shadow-popover w-full max-w-xl rounded-2xl bg-white p-6"><div className="flex justify-between"><h3 className="text-sm! font-semibold text-[#172B3A]">{rows.some(item => item.id === editor.id) ? "Edit" : "New"} inquiry</h3><button type="button" onClick={() => setEditor(null)} className="cursor-pointer"><XMarkIcon className="h-5 w-5 text-slate-500" /></button></div><form onSubmit={save} className="mt-5 space-y-4"><label className="block text-xs font-semibold text-slate-700">Reference *<input required value={editor.reference} onChange={event => setEditor({ ...editor, reference: event.target.value })} className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50/50 px-3 py-2.5 text-sm" /></label><label className="block text-xs font-semibold text-slate-700">Subject *<input required value={editor.subject} onChange={event => setEditor({ ...editor, subject: event.target.value })} className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50/50 px-3 py-2.5 text-sm" /></label><label className="block text-xs font-semibold text-slate-700">Status<select value={editor.status} onChange={event => setEditor({ ...editor, status: event.target.value as Inquiry["status"] })} className="mt-2 w-full rounded-xl border border-slate-200 bg-slate-50/50 px-3 py-2.5 text-sm">{Object.entries(inquiryStatuses).map(([key, value]) => <option key={key} value={key}>{value.label}</option>)}</select></label><div className="flex justify-end gap-2 border-t border-slate-100 pt-4"><button type="button" onClick={() => setEditor(null)} className="cursor-pointer rounded-lg px-3 py-2 text-xs font-semibold text-slate-600 hover:bg-slate-100">Cancel</button><button type="submit" className="cursor-pointer rounded-lg bg-[#FFA64D] px-4 py-2 text-xs font-semibold text-[#172B3A]">Save inquiry</button></div></form></div></div>}
  {deleting && <div className="fixed inset-0 z-50 grid place-items-center bg-[#172B3A]/40 p-4 backdrop-blur-sm"><div role="alertdialog" aria-modal="true" className="admin-shadow-popover w-full max-w-md rounded-2xl bg-white p-6"><h3 className="text-sm! font-semibold text-[#172B3A]">Delete inquiry?</h3><p className="mt-3 text-sm text-slate-500">Remove {deleting.reference} from this session?</p><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={() => setDeleting(null)} className="cursor-pointer rounded-lg px-3 py-2 text-xs font-semibold text-slate-600">Cancel</button><button type="button" onClick={() => { setRows(current => current.filter(item => item.id !== deleting.id)); setDeleting(null); }} className="cursor-pointer rounded-lg bg-red-600 px-4 py-2 text-xs font-semibold text-white">Delete</button></div></div></div>}
 </section>;
}
